version: '3.8'

services:
  mongo-express:
    image: mongo-express:1.0.0-alpha
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    networks:
      - order-network
    restart: always

  mongo:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    # volumes:
    #   - ./data:/data/db
    networks:
      - order-network
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - order-network
    restart: always

  create-order:
    depends_on:
      - rabbitmq
    build: ./create-order
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - order-network
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

networks:
  order-network:
    driver: bridge
